# Generated by Django 3.2 on 2024-01-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_company', models.CharField(max_length=100)),
                ('adress_management_company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Management_company_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adress', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('navigation_link_to_the_site', models.URLField()),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_site', to='domc.management_company')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment_building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_adress', models.CharField(max_length=200)),
                ('navigation_link_to_the_building', models.URLField()),
                ('management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='domc.management_company')),
                ('management_company_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_building', to='domc.management_company_site')),
            ],
        ),
    ]
