# Generated by Django 3.2 on 2024-01-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment_building',
            new_name='ApartmentBuilding',
        ),
        migrations.RenameModel(
            old_name='Management_company',
            new_name='ManagementCompany',
        ),
        migrations.RenameModel(
            old_name='Management_company_site',
            new_name='ManagementCompanySite',
        ),
    ]
