# Generated by Django 3.2 on 2024-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0002_auto_20240108_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompanysite',
            name='management_company_site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
