# Generated by Django 3.2 on 2024-01-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0003_managementcompanysite_management_company_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementcompany',
            name='management_company',
            field=models.CharField(max_length=100, verbose_name='Наименование управляющей компании'),
        ),
    ]
