# Generated by Django 3.2 on 2024-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0004_alter_managementcompany_management_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='navigation_link_to_the_company',
            field=models.URLField(default=1, verbose_name='Ссылка для построения маршрута к управляющей компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='adress_management_company',
            field=models.CharField(max_length=200, verbose_name='Адрес управляющей компании'),
        ),
    ]
