# Generated by Django 3.2 on 2024-01-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0005_auto_20240114_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='building_adress',
            field=models.CharField(max_length=200, verbose_name='Адрес МКД'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='management_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='domc.managementcompany', verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='management_company_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_building', to='domc.managementcompanysite', verbose_name='Наименование участка'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='navigation_link_to_the_building',
            field=models.URLField(verbose_name='Ссылка для построения маршрута к МКД'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='management_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_site', to='domc.managementcompany', verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='management_company_site',
            field=models.CharField(max_length=50, verbose_name='Наименование участка управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='navigation_link_to_the_site',
            field=models.URLField(verbose_name='Ссылка для построения маршрута к участку'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='note',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='site_adress',
            field=models.CharField(max_length=200, verbose_name='Адрес участка управляющей компании'),
        ),
    ]
