# Generated by Django 3.2 on 2024-01-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0006_auto_20240114_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentbuilding',
            options={'verbose_name': 'Многоквартирный жилой дом', 'verbose_name_plural': 'Многоквартирные жилые дома'},
        ),
        migrations.AlterModelOptions(
            name='managementcompany',
            options={'verbose_name': 'Управляющая компания', 'verbose_name_plural': 'Управляющие компании'},
        ),
        migrations.AlterModelOptions(
            name='managementcompanysite',
            options={'verbose_name': 'Участок управляющей компании', 'verbose_name_plural': 'Участки управляющей компании'},
        ),
    ]
