# Generated by Django 3.2 on 2024-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0007_auto_20240122_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='building_adress',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес МКД'),
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='management_company',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='management_company_site',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование участка управляющей компании'),
        ),
    ]
