# Generated by Django 3.2 on 2024-12-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0008_auto_20240128_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcompanysite',
            name='note',
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='in_contract',
            field=models.BooleanField(blank=True, help_text=('Выберите True, если МКД есть в договорк с управляющей ', 'компанией и False - если нет'), null=True, verbose_name='Наличие МКД в договоре с управляющей компанией'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='note',
            field=models.TextField(blank=True, help_text='Введите контаты и примечание по доступу', null=True, verbose_name='Контакты и примечание по доступу'),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='contact',
            field=models.TextField(blank=True, help_text='Введите контактные данные управляющей компании', null=True, verbose_name='Контакты управляющей компании'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='building_adress',
            field=models.CharField(help_text='Введите адрес МКД', max_length=200, unique=True, verbose_name='Адрес МКД'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='management_company',
            field=models.ForeignKey(help_text='Выберите управляющую компанию', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='domc.managementcompany', verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='management_company_site',
            field=models.ForeignKey(help_text='Выберите участок управляющей компании', on_delete=django.db.models.deletion.CASCADE, related_name='site_buildings', to='domc.managementcompanysite', verbose_name='Наименование участка управляющей компании'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='navigation_link_to_the_building',
            field=models.URLField(help_text='Укажите ссылку для построения маршрута МКД', verbose_name='Ссылка для построения маршрута к МКД'),
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='adress_management_company',
            field=models.CharField(help_text='Ведите адрес управляющей компании', max_length=200, verbose_name='Адрес управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='management_company',
            field=models.CharField(help_text='Введите наименование управляющей компании', max_length=100, unique=True, verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='navigation_link_to_the_company',
            field=models.URLField(help_text=('Укажите ссылку для построения маршрута к управляющей ', 'компании'), verbose_name='Ссылка для построения маршрута к управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='management_company',
            field=models.ForeignKey(help_text='Выберите управляющую компанию', on_delete=django.db.models.deletion.CASCADE, related_name='all_site', to='domc.managementcompany', verbose_name='Наименование управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='management_company_site',
            field=models.CharField(help_text='Введите наименование участка управляющей компании', max_length=50, unique=True, verbose_name='Наименование участка управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='navigation_link_to_the_site',
            field=models.URLField(help_text=('Укажите ссылку для построения маршрута к участку ', 'упарвляющей компании'), verbose_name='Ссылка для построения маршрута к участку'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='site_adress',
            field=models.CharField(help_text='Введите адрес участка управляющей компании', max_length=200, verbose_name='Адрес участка управляющей компании'),
        ),
    ]
