# Generated by Django 3.2 on 2024-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0010_auto_20241203_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='pipe_support_aria',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стойки Ария ТВ', null=True, verbose_name='Наличие стоки(ек) Ария ТВ на МКД'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='pipe_support_comlink',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стойки Комлинк', null=True, verbose_name='Наличие стоки(ек) Комлинк на МКД'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='pipe_support_oyster',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стойки Объединённых сетей', null=True, verbose_name='Наличие стоки(ек) Объединённых сетей на МКД'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='wall_mount_aria',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стеновое крепление Ария ТВ', null=True, verbose_name='Наличие стенового крепления Ария ТВ на МКД'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='wall_mount_comlink',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стеновое крепление Комлинк', null=True, verbose_name='Наличие стенового крепления Комлинк на МКД'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='wall_mount_oyster',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стеновое крепление Объединённых сетей', null=True, verbose_name='Наличие стенового крепления Объединённых сетей на МКД'),
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='in_contract',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли МКД в договоре с УК', null=True, verbose_name='Наличие МКД в договоре с УК'),
        ),
    ]
