# Generated by Django 4.2 on 2024-12-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0011_auto_20241203_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Введите контаты и примечание по доступу', null=True, verbose_name='Контакты и примечание по доступу')),
            ],
            options={
                'verbose_name': 'Комментарий по доступу на МКД',
                'verbose_name_plural': 'Комментарии по доступу на МКД',
            },
        ),
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='note',
            field=models.ForeignKey(blank=True, help_text='Введите контаты и примечание по доступу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_contact', to='domc.note', verbose_name='Контакты и примечание по доступу'),
        ),
    ]
