# Generated by Django 3.2 on 2024-12-08 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domc', '0012_note_alter_apartmentbuilding_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='apartmentbuilding',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='apartment_building',
            field=models.ForeignKey(default=1, help_text='Выберите адрес МКД', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='domc.apartmentbuilding', verbose_name='Адрес МКД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=1, help_text='Укажите автора заметки', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth.user', verbose_name='Автор заметки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2006-10-25 14:30:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default=1, help_text='Введите текст заметки', verbose_name='Текст заметки'),
            preserve_default=False,
        ),
    ]
