# Generated by Django 4.2 on 2025-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0013_auto_20241208_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentbuilding',
            name='management_company',
        ),
    ]
