# Generated by Django 4.2 on 2025-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0014_remove_apartmentbuilding_management_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbuilding',
            name='pipe_support_build',
            field=models.BooleanField(blank=True, help_text='Укажите есть ли на МКД стойки по проект у дома', null=True, verbose_name='Наличие стоки(ек) по проекту дома'),
        ),
    ]
