# Generated by Django 4.2 on 2025-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0015_apartmentbuilding_pipe_support_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentbuilding',
            name='navigation_link_to_the_building',
            field=models.URLField(blank=True, help_text='Укажите ссылку для построения маршрута к МКД', null=True, verbose_name='Ссылка для построения маршрута к МКД'),
        ),
        migrations.AlterField(
            model_name='managementcompany',
            name='navigation_link_to_the_company',
            field=models.URLField(blank=True, help_text='Укажите ссылку для построения маршрута к управляющей компании', null=True, verbose_name='Ссылка для построения маршрута к управляющей компании'),
        ),
        migrations.AlterField(
            model_name='managementcompanysite',
            name='navigation_link_to_the_site',
            field=models.URLField(blank=True, help_text='Укажите ссылку для построения маршрута к участку упарвляющей компании', null=True, verbose_name='Ссылка для построения маршрута к участку'),
        ),
    ]
