# Generated by Django 4.2 on 2025-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0016_alter_apartmentbuilding_navigation_link_to_the_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompanysite',
            name='office_phone',
            field=models.TextField(blank=True, help_text='Введите телефон эксплуатационного участка', null=True, verbose_name='Телефон эксплуатационного участка'),
        ),
        migrations.AddField(
            model_name='managementcompanysite',
            name='technician',
            field=models.TextField(blank=True, help_text='Введите ФИО техника эксплуатационного участка', null=True, verbose_name='Техник эксплуатационного участка'),
        ),
        migrations.AddField(
            model_name='managementcompanysite',
            name='technician_phone',
            field=models.TextField(blank=True, help_text='Введите номер телефона техника эксплуатационного участка', null=True, verbose_name='Телефон техника эксплуатационного участка'),
        ),
    ]
