# Generated by Django 4.2 on 2025-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domc', '0017_managementcompanysite_office_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcompanysite',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='managementcompanysite',
            name='technician_phone',
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='technician',
            field=models.TextField(blank=True, help_text='Введите ФИО техника эксплуатационного участка', null=True, verbose_name='Техник эксплуатационного участка'),
        ),
        migrations.AddField(
            model_name='apartmentbuilding',
            name='technician_phone',
            field=models.TextField(blank=True, help_text='Введите номер телефона техника эксплуатационного участка', null=True, verbose_name='Телефон техника эксплуатационного участка'),
        ),
    ]
